import os
import stat
import dbus

class DesktopLauncher:
    def __init__(self, apk_path, package_name):
        self.apk_path = apk_path
        self.package_name = package_name

    def generate_shell_launcher(self, output_dir):
        """Generates a standalone shell script to launch the APK."""
        os.makedirs(output_dir, exist_ok=True)
        launcher_script_path = os.path.join(output_dir, f"launch_{self.package_name}.sh")

        main_cli = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "cli", "main.py")

        script_content = f"""#!/bin/bash
# ARES Launcher Script for {self.package_name}
# Auto-generated by ARES Desktop Integration
python3 {main_cli} "{self.apk_path}"
"""
        with open(launcher_script_path, 'w') as f:
            f.write(script_content)

        # Make executable
        st = os.stat(launcher_script_path)
        os.chmod(launcher_script_path, st.st_mode | stat.S_IEXEC)

        return launcher_script_path

    def signal_dbus_launch(self):
        """Sends a dbus signal indicating the app was launched."""
        try:
            bus = dbus.SessionBus()
            # In Phase 2, we just emit a generic signal. We'll register a real bus name later.
            signal_object = bus.get_object('org.freedesktop.DBus', '/org/freedesktop/DBus')
            signal_interface = dbus.Interface(signal_object, 'org.freedesktop.DBus')
            # Currently just a stub/placeholder for actual routing
            return True
        except dbus.DBusException:
            return False

    @staticmethod
    def stub_xdg_open():
        """Compatibility layer stub for xdg-open."""
        # For phase 2, we just document the stub. In later phases, this will intercept
        # requests from the APK and map them to the real Linux xdg-open.
        pass
